version: '3.7'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=test-db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes:
          - postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./init-db/10-create-table.sql:/docker-entrypoint-initdb.d/10-create-table.sql
          - ./init-db/20-fill-table.sql:/docker-entrypoint-initdb.d/20-fill-table.sql
volumes: 
  postgres-data: