name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
  
    - name: Start containers
      run: docker-compose -f "docker-compose-oracle.yml" up -d --build

    # - name: Test
    #   run: go test -v ./...

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-oracle.yml" down

